#!/bin/bash


SOURCE_DIR="/actual/path/to/source_directory"
REMOTE_USER="username"
REMOTE_HOST="remote.server.com"
REMOTE_DIR="/path/to/remote_backup_directory"
LOG_FILE="/var/log/backup.log"


log_message() {
    local message="$1"
    echo "$message" | tee -a "$LOG_FILE"
}


if [ ! -d "$SOURCE_DIR" ]; then
    log_message "ERROR: Source directory $SOURCE_DIR does not exist."
    exit 1
fi


log_message "Starting backup from $SOURCE_DIR to $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR"
rsync -avz --delete "$SOURCE_DIR" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR" > /tmp/rsync_output.log 2>&1


if [ $? -eq 0 ]; then
    log_message "Backup completed successfully."
else
    log_message "ERROR: Backup failed. Check /tmp/rsync_output.log for details."
    exit 1
fi


rm /tmp/rsync_output.log


log_message "Backup process finished - $(date)"
log_message "--------------------------------------------------"

